[secrets]
  description = "Custom rules for Voidlink"

  [[secrets.passthrough]]
    type = "raw"
    target = "gitleaks.toml"
    value = """
[extend]
# The following line tells Gitleaks to use the default rules and append ours
useDefault = true

[[rules]]
id = "internal-domain-leak"
description = "Internal domain string detected (Prevent Domain Leakage)"
regex = '''INTERNAL_DOMAIN_REGEXP_PLACEHOLDER'''
tags = ["internal", "domain"]
"""
