build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - apk add --no-cache git
    -  # Replace placeholders for GitLab release
    - sed -i "s|[\$\$][\$\$]REPO_URL[\$\$][\$\$]|$CI_PROJECT_URL|g" Dockerfile README.md
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --driver-opt network=host
    - docker buildx build --platform linux/amd64,linux/arm64 --provenance=false -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --push .
